=== mat3ra/esse/schema/materials_category/multi_material/interfaces/twisted/configuration.json
{
  "$id": "materials-category/multi-material/interfaces/twisted/configuration",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Twisted Interface Configuration",
  "description": "Configuration for creating a twisted interface between two layers",
  "type": "object",
  "required": ["film"],
  "properties": {
    "film": {
      "description": "The film material",
      "$ref": "../../../../material.json"
    },
    "substrate": {
      "description": "The substrate material",
      "$comment": "Substrate is optional, in case of absence, copy of film is used instead",
      "$ref": "../../../../material.json"
    },
    "twist_angle": {
      "description": "Twist angle in degrees",
      "type": "number",
      "default": 0.0
    },
    "distance_z": {
      "description": "Vertical distance between layers in Angstroms",
      "type": "number",
      "minimum": 0,
      "default": 3.0
    },
    "vacuum": {
      "$ref": "../../../../core/reusable/material/slab/vacuum.json"
    }
  }
}

=== mat3ra/esse/dist/js/example/materials_category/multi_material/interfaces/twisted/configuration.json
{
    "film": {
        "_id": "LCthJ6E2QabYCZqf3",
        "basis": {
            "coordinates": [
                {
                    "id": 1,
                    "value": [
                        0,
                        0,
                        0
                    ]
                },
                {
                    "id": 2,
                    "value": [
                        0.25,
                        0.25,
                        0.25
                    ]
                }
            ],
            "elements": [
                {
                    "id": 1,
                    "value": "Si"
                },
                {
                    "id": 2,
                    "value": "Si"
                }
            ],
            "name": "basis",
            "units": "crystal"
        },
        "createdAt": "2016-04-03T05:25:37.430Z",
        "creator": {
            "_id": "HtxACY2wX4b2hS8Rv",
            "cls": "User",
            "slug": "exadmin"
        },
        "derivedProperties": [
            {
                "name": "volume",
                "units": "angstrom^3",
                "value": 131.1
            },
            {
                "name": "density",
                "units": "g/cm^3",
                "value": 2.33
            },
            {
                "name": "symmetry",
                "spaceGroupSymbol": "Fd-3m",
                "tolerance": {
                    "units": "angstrom",
                    "value": 0.3
                }
            },
            {
                "degree": 10,
                "name": "p-norm",
                "value": 0.71
            },
            {
                "element": "Si",
                "name": "elemental_ratio",
                "value": 0.71
            },
            {
                "name": "inchi",
                "value": ""
            },
            {
                "name": "inchi_key",
                "value": ""
            }
        ],
        "exabyteId": "RKiswuxHKkF3uvLyA",
        "formula": "Si",
        "hash": "4ac3fa057e3530628eb1295c77110eaa",
        "isDefault": false,
        "isNonPeriodic": false,
        "lattice": {
            "name": "lattice",
            "vectors": {
                "a": [
                    5,
                    0.000121312,
                    0.000131415
                ],
                "alat": 1,
                "b": [
                    0.000121312,
                    5,
                    0.000121314
                ],
                "c": [
                    0.000121313,
                    0.000121312,
                    5
                ],
                "units": "angstrom"
            },
            "a": 5.14,
            "alpha": 90,
            "b": 5.14,
            "beta": 90,
            "c": 5.14,
            "gamma": 90,
            "type": "CUB",
            "units": {
                "angle": "degree",
                "length": "angstrom"
            }
        },
        "name": "Silicon FCC",
        "owner": {
            "_id": "HtxACY2wX4b2hS8Rv",
            "cls": "Account",
            "slug": "exabyte"
        },
        "scaledHash": "5bd4eb168e3530628eb1295d88221cbb",
        "schemaVersion": "0.2.0",
        "slug": "silicon-fcc",
        "unitCellFormula": "Si2",
        "updatedAt": "2016-04-04T17:58:42.867Z"
    },
    "substrate": {
        "_id": "LCthJ6E2QabYCZqf3",
        "basis": {
            "coordinates": [
                {
                    "id": 1,
                    "value": [
                        0,
                        0,
                        0
                    ]
                },
                {
                    "id": 2,
                    "value": [
                        0.25,
                        0.25,
                        0.25
                    ]
                }
            ],
            "elements": [
                {
                    "id": 1,
                    "value": "Si"
                },
                {
                    "id": 2,
                    "value": "Si"
                }
            ],
            "name": "basis",
            "units": "crystal"
        },
        "createdAt": "2016-04-03T05:25:37.430Z",
        "creator": {
            "_id": "HtxACY2wX4b2hS8Rv",
            "cls": "User",
            "slug": "exadmin"
        },
        "derivedProperties": [
            {
                "name": "volume",
                "units": "angstrom^3",
                "value": 131.1
            },
            {
                "name": "density",
                "units": "g/cm^3",
                "value": 2.33
            },
            {
                "name": "symmetry",
                "spaceGroupSymbol": "Fd-3m",
                "tolerance": {
                    "units": "angstrom",
                    "value": 0.3
                }
            },
            {
                "degree": 10,
                "name": "p-norm",
                "value": 0.71
            },
            {
                "element": "Si",
                "name": "elemental_ratio",
                "value": 0.71
            },
            {
                "name": "inchi",
                "value": ""
            },
            {
                "name": "inchi_key",
                "value": ""
            }
        ],
        "exabyteId": "RKiswuxHKkF3uvLyA",
        "formula": "Si",
        "hash": "4ac3fa057e3530628eb1295c77110eaa",
        "isDefault": false,
        "isNonPeriodic": false,
        "lattice": {
            "name": "lattice",
            "vectors": {
                "a": [
                    5,
                    0.000121312,
                    0.000131415
                ],
                "alat": 1,
                "b": [
                    0.000121312,
                    5,
                    0.000121314
                ],
                "c": [
                    0.000121313,
                    0.000121312,
                    5
                ],
                "units": "angstrom"
            },
            "a": 5.14,
            "alpha": 90,
            "b": 5.14,
            "beta": 90,
            "c": 5.14,
            "gamma": 90,
            "type": "CUB",
            "units": {
                "angle": "degree",
                "length": "angstrom"
            }
        },
        "name": "Silicon FCC",
        "owner": {
            "_id": "HtxACY2wX4b2hS8Rv",
            "cls": "Account",
            "slug": "exabyte"
        },
        "scaledHash": "5bd4eb168e3530628eb1295d88221cbb",
        "schemaVersion": "0.2.0",
        "slug": "silicon-fcc",
        "unitCellFormula": "Si2",
        "updatedAt": "2016-04-04T17:58:42.867Z"
    },
    "twist_angle": 30,
    "distance_z": 3,
    "vacuum": 15
}
