=== mat3ra/esse/schema/materials_category/defects/two_dimensional/slab_grain_boundary/configuration.json
{
    "$id": "materials-category/defects/two-dimensional/slab-grain-boundary/configuration",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Slab Grain Boundary Configuration Schema",
    "description": "Configuration for a grain boundary between two phases with different surfaces facing each other",
    "type": "object",
    "required": [
        "phase_1_configuration",
        "phase_2_configuration",
        "phase_1_termination",
        "phase_2_termination",
        "slab_configuration"
    ],
    "properties": {
        "phase_1_configuration": {
            "description": "The configuration of the first phase",
            "$ref": "../../../single_material/two_dimensional/slab/configuration.json"
        },
        "phase_2_configuration": {
            "description": "The configuration of the second phase",
            "$ref": "../../../single_material/two_dimensional/slab/configuration.json"
        },
        "phase_1_termination": {
            "description": "The termination of the first phase",
            "$ref": "../../../../material/reusable/slab/termination.json"
        },
        "phase_2_termination": {
            "description": "The termination of the second phase",
            "$ref": "../../../../material/reusable/slab/termination.json"
        },
        "gap": {
            "description": "The gap between the two phases, in Angstroms",
            "type": "number",
            "default": 3.0
        },
        "slab_configuration": {
            "description": "The configuration of the grain boundary slab",
            "$ref": "../../../single_material/two_dimensional/slab/configuration.json"
        },
        "slab_termination": {
            "description": "The termination of the grain boundary slab",
            "$ref": "../../../../material/reusable/slab/termination.json"
        }
    }
}

=== mat3ra/esse/dist/js/example/materials_category/defects/two_dimensional/slab_grain_boundary/configuration.json
{
    "phase_1_configuration": {
        "bulk": {
            "_id": "LCthJ6E2QabYCZqf3",
            "basis": {
                "coordinates": [
                    {
                        "id": 1,
                        "value": [
                            0,
                            0,
                            0
                        ]
                    },
                    {
                        "id": 2,
                        "value": [
                            0.25,
                            0.25,
                            0.25
                        ]
                    }
                ],
                "elements": [
                    {
                        "id": 1,
                        "value": "Si"
                    },
                    {
                        "id": 2,
                        "value": "Si"
                    }
                ],
                "name": "basis",
                "units": "crystal"
            },
            "createdAt": "2016-04-03T05:25:37.430Z",
            "creator": {
                "_id": "HtxACY2wX4b2hS8Rv",
                "cls": "User",
                "slug": "exadmin"
            },
            "derivedProperties": [
                {
                    "name": "volume",
                    "units": "angstrom^3",
                    "value": 131.1
                },
                {
                    "name": "density",
                    "units": "g/cm^3",
                    "value": 2.33
                },
                {
                    "name": "symmetry",
                    "spaceGroupSymbol": "Fd-3m",
                    "tolerance": {
                        "units": "angstrom",
                        "value": 0.3
                    }
                },
                {
                    "degree": 10,
                    "name": "p-norm",
                    "value": 0.71
                },
                {
                    "element": "Si",
                    "name": "elemental_ratio",
                    "value": 0.71
                },
                {
                    "name": "inchi",
                    "value": ""
                },
                {
                    "name": "inchi_key",
                    "value": ""
                }
            ],
            "exabyteId": "RKiswuxHKkF3uvLyA",
            "formula": "Si",
            "hash": "4ac3fa057e3530628eb1295c77110eaa",
            "isDefault": false,
            "isNonPeriodic": false,
            "lattice": {
                "name": "lattice",
                "vectors": {
                    "a": [
                        5,
                        0.000121312,
                        0.000131415
                    ],
                    "alat": 1,
                    "b": [
                        0.000121312,
                        5,
                        0.000121314
                    ],
                    "c": [
                        0.000121313,
                        0.000121312,
                        5
                    ],
                    "units": "angstrom"
                },
                "a": 5.14,
                "alpha": 90,
                "b": 5.14,
                "beta": 90,
                "c": 5.14,
                "gamma": 90,
                "type": "CUB",
                "units": {
                    "angle": "degree",
                    "length": "angstrom"
                }
            },
            "name": "Silicon FCC",
            "owner": {
                "_id": "HtxACY2wX4b2hS8Rv",
                "cls": "Account",
                "slug": "exabyte"
            },
            "scaledHash": "5bd4eb168e3530628eb1295d88221cbb",
            "schemaVersion": "0.2.0",
            "slug": "silicon-fcc",
            "unitCellFormula": "Si2",
            "updatedAt": "2016-04-04T17:58:42.867Z"
        },
        "miller_indices": [
            1,
            0,
            0
        ],
        "thickness": 3,
        "vacuum": 15
    },
    "phase_2_configuration": {
        "bulk": {
            "_id": "LCthJ6E2QabYCZqf3",
            "basis": {
                "coordinates": [
                    {
                        "id": 1,
                        "value": [
                            0,
                            0,
                            0
                        ]
                    },
                    {
                        "id": 2,
                        "value": [
                            0.25,
                            0.25,
                            0.25
                        ]
                    }
                ],
                "elements": [
                    {
                        "id": 1,
                        "value": "Si"
                    },
                    {
                        "id": 2,
                        "value": "Si"
                    }
                ],
                "name": "basis",
                "units": "crystal"
            },
            "createdAt": "2016-04-03T05:25:37.430Z",
            "creator": {
                "_id": "HtxACY2wX4b2hS8Rv",
                "cls": "User",
                "slug": "exadmin"
            },
            "derivedProperties": [
                {
                    "name": "volume",
                    "units": "angstrom^3",
                    "value": 131.1
                },
                {
                    "name": "density",
                    "units": "g/cm^3",
                    "value": 2.33
                },
                {
                    "name": "symmetry",
                    "spaceGroupSymbol": "Fd-3m",
                    "tolerance": {
                        "units": "angstrom",
                        "value": 0.3
                    }
                },
                {
                    "degree": 10,
                    "name": "p-norm",
                    "value": 0.71
                },
                {
                    "element": "Si",
                    "name": "elemental_ratio",
                    "value": 0.71
                },
                {
                    "name": "inchi",
                    "value": ""
                },
                {
                    "name": "inchi_key",
                    "value": ""
                }
            ],
            "exabyteId": "RKiswuxHKkF3uvLyA",
            "formula": "Si",
            "hash": "4ac3fa057e3530628eb1295c77110eaa",
            "isDefault": false,
            "isNonPeriodic": false,
            "lattice": {
                "name": "lattice",
                "vectors": {
                    "a": [
                        5,
                        0.000121312,
                        0.000131415
                    ],
                    "alat": 1,
                    "b": [
                        0.000121312,
                        5,
                        0.000121314
                    ],
                    "c": [
                        0.000121313,
                        0.000121312,
                        5
                    ],
                    "units": "angstrom"
                },
                "a": 5.14,
                "alpha": 90,
                "b": 5.14,
                "beta": 90,
                "c": 5.14,
                "gamma": 90,
                "type": "CUB",
                "units": {
                    "angle": "degree",
                    "length": "angstrom"
                }
            },
            "name": "Silicon FCC",
            "owner": {
                "_id": "HtxACY2wX4b2hS8Rv",
                "cls": "Account",
                "slug": "exabyte"
            },
            "scaledHash": "5bd4eb168e3530628eb1295d88221cbb",
            "schemaVersion": "0.2.0",
            "slug": "silicon-fcc",
            "unitCellFormula": "Si2",
            "updatedAt": "2016-04-04T17:58:42.867Z"
        },
        "miller_indices": [
            1,
            1,
            0
        ],
        "thickness": 3,
        "vacuum": 15
    },
    "phase_1_termination": {
        "chemical_elements": "Si",
        "space_group_symmetry_label": "P4/mmm_2"
    },
    "phase_2_termination": {
        "chemical_elements": "Si",
        "space_group_symmetry_label": "P4/mmm_2"
    },
    "gap": 2.5,
    "slab_configuration": {
        "miller_indices": [
            0,
            0,
            1
        ],
        "thickness": 3,
        "vacuum": 15
    },
    "slab_termination": {
        "chemical_elements": "Si",
        "space_group_symmetry_label": "P4/mmm_2"
    }
}
